version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew build
  release:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew bintrayUpload

workflows:
  version: 2
  build-test-and-release:
    jobs:
      - build
      - approve-release:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - release:
          requires:
            - approve-release
          filters:
            branches:
              only: master
