name: Gradle Test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Test with Gradle
        run: |
          ./gradlew clean build -x test publishToMavenLocal
          ./gradlew clean build test
        continue-on-error: true

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: |
            build/gradle/reports/**/*
